# Generated by Django 5.2.1 on 2025-10-01 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('advisor', models.CharField(blank=True, max_length=100, null=True)),
                ('productions_name', models.CharField(max_length=100)),
                ('production_type', models.CharField(max_length=100)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('seat_preference', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='perfomance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_tickets_sold', models.IntegerField()),
                ('date_of_perfomance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(max_length=100)),
                ('production_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='customer_assigned',
        ),
        migrations.AddField(
            model_name='advisor',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
